import { JsonRpcSigner, Web3Provider } from "@ethersproject/providers";
import { ethers } from "ethers";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/index.module.css";
import { Lottery, Lottery__factory } from "../../web3/typechain";

declare let window: {
  ethereum: ethers.providers.ExternalProvider;
};

const Home: NextPage = () => {
  const [provider, setProvider] = useState<Web3Provider>();
  const [contract, setContract] = useState<Lottery | null>();
  const [signer, setSigner] = useState<JsonRpcSigner>();
  const [address, setAddress] = useState<string | undefined>();
  const [error, setError] = useState<string>();

  const handleConnectWallet = async () => {
    if (
      typeof window !== "undefined" &&
      typeof window.ethereum !== "undefined"
    ) {
      try {
        const provider = new ethers.providers.Web3Provider(window.ethereum);
        const contract = Lottery__factory.connect(
          process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as string,
          provider
        );
        const signer = provider.getSigner();
        const currentAddress = await signer.getAddress();

        setProvider(provider);
        setContract(contract);
        setSigner(signer);
        setAddress(currentAddress);
      } catch (error) {
        if (error instanceof Error) setError(error.message);
      }
    }
  };

  const handleDisconnectWallet = () => setAddress(undefined);

  return (
    <div>
      <Head>
        <title>Lottery Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <h1 className={styles.title}>Next Lottery Dapp</h1>
        <button
          onClick={address ? handleDisconnectWallet : handleConnectWallet}
        >
          {address ? "Logout" : "Connect Wallet"}
        </button>
      </nav>
      <main>
        <p>Enter the lottery by sending 0.01 Ether</p>
      </main>
    </div>
  );
};

export default Home;
