import { JsonRpcSigner, Web3Provider } from "@ethersproject/providers";
import { ethers } from "ethers";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Lottery__factory } from "../typechain";

const Home: NextPage = () => {
  const [provider, setProvider] = useState<Web3Provider>();
  const [signer, setSigner] = useState<JsonRpcSigner>();
  const [address, setAddress] = useState<string | null>();

  const handleConnectWallet = async () => {
    if (provider && !address) {
      await provider.send("eth_requestAccounts", []);
      const signer = provider.getSigner();
      const currentAddress = await signer.getAddress();

      setSigner(signer);
      setAddress(currentAddress);
    } else {
      setAddress(null);
    }
  };

  useEffect(() => {
    const provider =
      typeof window === "undefined" || !window.ethereum
        ? null
        : new ethers.providers.Web3Provider(window.ethereum);

    if (provider) {
      setProvider(provider);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Lottery Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <h1>Next Lottery Dapp</h1>
          <button onClick={handleConnectWallet}>
            {address ? "Logout" : "Connect Wallet"}
          </button>
        </nav>
      </main>
    </div>
  );
};

export default Home;
